// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ReadMore from 'stimulus-read-more'

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)

import TurboModalController from "./turbo_modal_controller.js"
application.register("turbo_modal", TurboModalController)

import DebounceController from "./debounce_controller.js"
application.register("debounce", DebounceController)

import ToastController from "./toast_controller.js"
application.register("toast", ToastController)

import PresentHandlerController from "./present_handler_controller.js"
application.register("present_handler", PresentHandlerController)

application.register('read-more', ReadMore)
