version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      env_file: .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

  sidekiq:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: bundle exec sidekiq --environment development -C config/sidekiq.yml 
    links:
      - postgres
      - redis
    volumes:
      - ../../:/myapp
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_MASTER_KEY={{ vault_rails_master_key }}
      - RAILS_ENV=production
      - DATABASE_HOST={{database.database_host}}
      - POSTGRES_USER={{database.postgres_user}}
      - POSTGRES_PASSWORD={{database.postgres_password}}
      - POSTGRES_DB={{database.postgres_db}}

  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
