version: "3.3"
services:
  app:
    build:
      context: .
    command: sh -c "bundle exec puma -C config/puma.rb"
    # Best way to store sensentive values in env
    # env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - PARALLEL_WORKERS=1
    volumes:
      - .:/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
    # Best way to store sensentive values in env
    # env_file: .env
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq --environment development -C config/sidekiq.yml 
    links:
      - postgres
      - redis
    volumes:
      - ../../:/myapp
    # Best way to store sensentive values in env
    # env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - PARALLEL_WORKERS=1
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
