development:
  adapter: redis
  url: redis://localhost:6379/9
  channel_prefix: dev

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_CABLE_URL'] %>
  channel_prefix: feed_news_production
